export interface ExerciseOption {
  name: string;
  isBodyweight: boolean;
}

// Per-category exercise options sourced from the SBS spreadsheet dropdowns.
// Vanity slots have no predefined list (open text).
export const EXERCISE_OPTIONS: Record<string, ExerciseOption[]> = {
  'Compound, pec-dominant': [
    { name: 'dumbbell bench press', isBodyweight: false },
    { name: 'bench press', isBodyweight: false },
    { name: 'dumbbell incline press', isBodyweight: false },
    { name: 'incline press', isBodyweight: false },
    { name: 'machine chest press', isBodyweight: false },
    { name: 'machine incline press', isBodyweight: false },
    { name: 'dips', isBodyweight: true },
    { name: 'push-ups', isBodyweight: true },
  ],
  'Compound, shoulder-dominant': [
    { name: 'seated dumbbell shoulder press', isBodyweight: false },
    { name: 'machine shoulder press', isBodyweight: false },
    { name: 'standing shoulder press', isBodyweight: false },
    { name: 'standing dumbbell shoulder press', isBodyweight: false },
    { name: 'seated shoulder press', isBodyweight: false },
    { name: 'barbell push press', isBodyweight: false },
    { name: 'dumbbell push press', isBodyweight: false },
  ],
  'Upper back horizontal': [
    { name: 'bent over row', isBodyweight: false },
    { name: 'barbell row', isBodyweight: false },
    { name: 'seated cable row', isBodyweight: false },
    { name: 'one-arm dumbbell row', isBodyweight: false },
    { name: 't-bar row', isBodyweight: false },
    { name: 'chest-supported row', isBodyweight: false },
    { name: 'chest-supported dumbbell row', isBodyweight: false },
    { name: 'machine row', isBodyweight: false },
  ],
  'Upper back vertical': [
    { name: 'neutral grip pull-up', isBodyweight: true },
    { name: 'pull-up', isBodyweight: true },
    { name: 'chin-up', isBodyweight: true },
    { name: 'reverse grip pull-down', isBodyweight: false },
    { name: 'pull-down', isBodyweight: false },
    { name: 'neutral grip pull-down', isBodyweight: false },
    { name: 'machine pull-down', isBodyweight: false },
  ],
  'Hip-dominant': [
    { name: 'romanian deadlift', isBodyweight: false },
    { name: 'back extension', isBodyweight: false },
    { name: 'deadlift', isBodyweight: false },
    { name: 'stiff-legged deadlift', isBodyweight: false },
    { name: 'trap bar deadlift', isBodyweight: false },
    { name: 'sumo deadlift', isBodyweight: false },
    { name: 'glute-ham raise', isBodyweight: false },
    { name: 'good morning', isBodyweight: false },
  ],
  'Knee-dominant': [
    { name: 'barbell squat', isBodyweight: false },
    { name: 'leg press', isBodyweight: false },
    { name: 'barbell front squat', isBodyweight: false },
    { name: 'machine hack squat', isBodyweight: false },
    { name: 'smith machine squat', isBodyweight: false },
  ],
  'Hip-dominant accessory': [
    { name: 'seated hamstrings curl', isBodyweight: false },
    { name: 'lying hamstrings curl', isBodyweight: false },
    { name: 'standing hamstrings curl', isBodyweight: false },
    { name: 'weighted hip thrust', isBodyweight: false },
    { name: 'weighted glute bridge', isBodyweight: false },
    { name: 'back raise', isBodyweight: false },
    { name: 'single leg RDL', isBodyweight: false },
  ],
  'Quad-dominant accessory': [
    { name: 'split squats', isBodyweight: false },
    { name: 'knee extensions', isBodyweight: false },
    { name: 'step-ups', isBodyweight: false },
    { name: 'walking lunges', isBodyweight: false },
    { name: 'reverse lunges', isBodyweight: false },
  ],
  'Calves': [
    { name: 'leg press calf raises', isBodyweight: false },
    { name: 'seated calf raises', isBodyweight: false },
    { name: 'standing calf raise machine', isBodyweight: false },
    { name: 'smith machine calf raises', isBodyweight: false },
    { name: 'smith machine calf raises (toes elevated)', isBodyweight: false },
  ],
  // 'Vanity' intentionally omitted — open text input only
};

export interface DefaultExercise {
  id: string;
  name: string;
  category: string;
  is_bodyweight: boolean;
  rounding: number;
  sort_order: number;
  starting_sets: number;
  ending_sets: number;
  starting_reps: number | null;
  ending_reps: number | null;
  set_increase: number;
  reps_per_set_increase: number;
  weight_increase: number | null;
}

export const DEFAULT_EXERCISES: DefaultExercise[] = [
  {
    id: 'dumbbell_bench_press',
    name: 'dumbbell bench press',
    category: 'Compound, pec-dominant',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 0,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'dumbbell_incline_press',
    name: 'dumbbell incline press',
    category: 'Compound, pec-dominant',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 1,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'seated_dumbbell_shoulder_press',
    name: 'seated dumbbell shoulder press',
    category: 'Compound, shoulder-dominant',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 2,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'machine_shoulder_press',
    name: 'machine shoulder press',
    category: 'Compound, shoulder-dominant',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 3,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'bent_over_row',
    name: 'bent over row',
    category: 'Upper back horizontal',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 4,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'seated_cable_row',
    name: 'seated cable row',
    category: 'Upper back horizontal',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 5,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'neutral_grip_pull_up',
    name: 'neutral grip pull-up',
    category: 'Upper back vertical',
    is_bodyweight: true,
    rounding: 5,
    sort_order: 6,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: null,
    ending_reps: null,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: null,
  },
  {
    id: 'reverse_grip_pull_down',
    name: 'reverse grip pull-down',
    category: 'Upper back vertical',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 7,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'romanian_deadlift',
    name: 'romanian deadlift',
    category: 'Hip-dominant',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 8,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'back_extension',
    name: 'back extension',
    category: 'Hip-dominant',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 9,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'barbell_squat',
    name: 'barbell squat',
    category: 'Knee-dominant',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 10,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'leg_press',
    name: 'leg press',
    category: 'Knee-dominant',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 11,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'seated_hamstrings_curl',
    name: 'seated hamstrings curl',
    category: 'Hip-dominant accessory',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 12,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'split_squats',
    name: 'split squats',
    category: 'Quad-dominant accessory',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 13,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'leg_press_calf_raises',
    name: 'leg press calf raises',
    category: 'Calves',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 14,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'seated_calf_raises',
    name: 'seated calf raises',
    category: 'Calves',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 15,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'preacher_curls',
    name: 'preacher curls',
    category: 'Vanity',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 16,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'skullcrushers',
    name: 'skullcrushers',
    category: 'Vanity',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 17,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'dumbbell_rear_delt_raises',
    name: 'dumbbell rear delt raises',
    category: 'Vanity',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 18,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'barbell_shrugs',
    name: 'barbell shrugs',
    category: 'Vanity',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 19,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'dumbbell_flyes',
    name: 'dumbbell flyes',
    category: 'Vanity',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 20,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
  {
    id: 'dumbbell_side_delt_raises',
    name: 'dumbbell side delt raises',
    category: 'Vanity',
    is_bodyweight: false,
    rounding: 5,
    sort_order: 21,
    starting_sets: 3,
    ending_sets: 5,
    starting_reps: 8,
    ending_reps: 12,
    set_increase: 1,
    reps_per_set_increase: 2,
    weight_increase: 0.1,
  },
];

export const SPLITS: Record<number, Record<number, string[]>> = {
  3: {
    1: [
      'dumbbell_bench_press',
      'bent_over_row',
      'machine_shoulder_press',
      'reverse_grip_pull_down',
      'dumbbell_incline_press',
      'seated_cable_row',
      'preacher_curls',
      'skullcrushers',
    ],
    2: [
      'barbell_squat',
      'romanian_deadlift',
      'leg_press',
      'back_extension',
      'split_squats',
      'leg_press_calf_raises',
      'dumbbell_rear_delt_raises',
    ],
    3: [
      'seated_dumbbell_shoulder_press',
      'neutral_grip_pull_up',
      'seated_hamstrings_curl',
      'seated_calf_raises',
      'barbell_shrugs',
      'dumbbell_flyes',
      'dumbbell_side_delt_raises',
    ],
  },
  4: {
    1: [
      'dumbbell_bench_press',
      'bent_over_row',
      'machine_shoulder_press',
      'reverse_grip_pull_down',
      'preacher_curls',
      'skullcrushers',
    ],
    2: [
      'barbell_squat',
      'back_extension',
      'split_squats',
      'leg_press_calf_raises',
      'dumbbell_rear_delt_raises',
    ],
    3: [
      'seated_dumbbell_shoulder_press',
      'neutral_grip_pull_up',
      'dumbbell_incline_press',
      'seated_cable_row',
      'barbell_shrugs',
      'dumbbell_flyes',
    ],
    4: [
      'romanian_deadlift',
      'leg_press',
      'seated_hamstrings_curl',
      'seated_calf_raises',
      'dumbbell_side_delt_raises',
    ],
  },
  5: {
    1: ['dumbbell_bench_press', 'bent_over_row', 'machine_shoulder_press', 'reverse_grip_pull_down'],
    2: ['barbell_squat', 'back_extension', 'split_squats', 'leg_press_calf_raises'],
    3: [
      'seated_dumbbell_shoulder_press',
      'neutral_grip_pull_up',
      'dumbbell_incline_press',
      'seated_cable_row',
    ],
    4: ['romanian_deadlift', 'leg_press', 'seated_hamstrings_curl', 'seated_calf_raises'],
    5: [
      'preacher_curls',
      'skullcrushers',
      'dumbbell_rear_delt_raises',
      'barbell_shrugs',
      'dumbbell_flyes',
      'dumbbell_side_delt_raises',
    ],
  },
};
